# Generated by Django 3.0.8 on 2020-07-23 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeevent',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='stripeevent',
            name='user',
        ),
    ]
