# Generated by Django 4.0.6 on 2022-07-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0005_stripeinfo_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeevent',
            name='event_id',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='stripeevent',
            name='object_id',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
